apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: php-phalcon
  name: php-phalcon
spec:
  output:
    to:
      kind: ImageStreamTag
      name: php-phalcon:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/weepee-org/openshift-example-project.git
    contextDir: php-phalcon/
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: php-phalcon-webserver:latest
        namespace: weepee-registry
    type: Docker
