apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  output:
    to:
      kind: ImageStreamTag
      name: wordpress:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/weepee-org/openshift-example-project.git
    contextDir: wordpress-php/
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: wordpress-php-app:latest
        namespace: weepee-registry
    type: Docker
