apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  output:
    to:
      kind: ImageStreamTag
      name: proxy:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/weepee-org/openshift-example-project.git
    contextDir: proxy/
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: proxy-server:latest
        namespace: weepee-registry
    type: Docker
