apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: memsql0
  name: memsql0
spec:
  output:
    to:
      kind: ImageStreamTag
      name: memsql0:latest
  resources: {}
  source:
    git:
      ref: master
      uri: https://github.com/weepee-org/openshift-example-project.git
    contextDir: memsql0/
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: memsql-server:latest
        namespace: weepee-registry
    type: Docker
