apiVersion: v1
kind: Service
metadata:
  labels:
    app: mojo
  name: mojo
spec:
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mojo
    deploymentconfig: mojo
  sessionAffinity: None
  type: ClusterIP
